//--------------------------------------------------------------------------------
// Generated by tools/export_assets.py
//--------------------------------------------------------------------------------

#pragma once
#include "Graphics.h"

struct GameAssets {
	
	TextureAsset *Background;
	ImageAsset *background;
	
	TextureAsset *Sprites;
	ImageAsset *camel;
	ImageAsset *camel_hump;
	ImageAsset *camel_jump;
	ImageAsset *camel_walk;
	ImageAsset *gazer_body;
	ImageAsset *gazer_eyeball;
	ImageAsset *gazer_iris;
	ImageAsset *bomb;
	ImageAsset *bomb_bounce;
	ImageAsset *combo;
	
	FontAsset *flixel;
	TilemapAsset *level;
	
	SampleAsset *jump;
	SampleAsset *juggle;
	SampleAsset *hit;
	
};


