//--------------------------------------------------------------------------------
// Generated by tools/export_assets.py
//--------------------------------------------------------------------------------

#pragma once
#include "Graphics.h"

struct GameAssets {
	
	TextureAsset *Sprites;
	ImageAsset *camel;
	ImageAsset *hump;
	
	FontAsset *flixel;
	
	SampleAsset *jump;
	
};


